routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});
//
use App\Events\WebsocketDemoEvent;
use App\Http\Controllers\HomeController;

Route::prefix('admin')->middleware('auth:web')->middleware('canAdmin')->group( function () {
    Route::get('/', 'admin\TrackController@index')->name('admin');
    Route::resource('track', 'admin\TrackController');
    Route::post('track/bulkStore', 'admin\TrackController@bulkStore')->name('track.bulkStore');
    Route::post('track/setCurrent', 'admin\TrackController@setCurrent')->name('track.setCurrent');

    Route::resource('page', 'admin\PageController')->only(['edit', 'update', 'index']);
    Route::resource('text', 'admin\TextController')->except(['destroy']);
    Route::resource('newArticle', 'admin\NewArticleController')->except(['show']);

    Route::resource('user', 'admin\UserController')->only(['index']);
    Route::patch('user/{user}/ban', 'admin\UserController@ban')->name('user.ban');
    Route::patch('user/{user}/un-ban', 'admin\UserController@unBan')->name('user.un-ban');

    Route::resource('message', 'admin\MessageController')->except(['show', 'create']);

    Route::resource('message', 'admin\MessageController')->except(['show']);
    Route::resource('shortNew', 'admin\ShortNewController')->except(['show']);
});

Auth::routes();
Route::get('auth/facebook', 'Auth\AuthController@loginFacebook')->name('auth-facebook');
Route::get('auth/facebook/callback', 'Auth\AuthController@userFromFacebook');
Route::get('auth/google', 'Auth\AuthController@loginGoogle')->name('auth-google');
Route::get('auth/google/callback', 'Auth\AuthController@userFromGoogle');

Route::get('data/update-tracks', 'DataController@updateTracksData')
//    ->middleware('auth:web')->middleware('canAdmin')
    ->name('update-data-tracks');

Route::get('/', 'HomeController@index');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/user/{id}/profile', 'UserController@profile')->name('user.profile');
Route::get('/home/ajax-track-popup/{track}', 'HomeController@ajaxTrackPopup')->name('home.ajax-track-popup');
Route::get('/home/ajax-track-popup/', 'HomeController@ajaxTrackPopup')->name('home.ajax-track-popup2');
Route::get('/home/ajax-tracks-by-bounds/', 'HomeController@ajaxGetTracks')->name('home.ajax-tracks-by-bounds');
Route::post('/home/ajax-update-position/', 'HomeController@ajaxUpdateCurrentPosition')
    ->middleware('auth:web')
    ->middleware('isTracking')
    ->name('home.ajax-update-position');
Route::get('/page/{slug}/', 'HomeController@page')->name('page');
Route::get('/rating/', 'HomeController@rating')->name('rating');

Route::get('/news/', 'HomeController@news')->name('news');
Route::get('/new/{id}', 'HomeController@singleNew')->name('single-new');

Route::prefix('user')->middleware('auth:web')->group( function () {
    Route::patch('{id}/update', 'UserController@update')->name('user.update');
    Route::patch('{id}/ajax-update', 'UserController@ajaxUpdate')->name('user.ajax-update');
    Route::patch('{user}/track-update/{track}', 'UserController@trackUpdate')->name('user.track-update');
});

Route::prefix('order')->middleware('auth:web')->group( function () {
    Route::patch('track/{track}/reserve', 'OrderController@reserve')->name('track.reserve');
    Route::patch('track/{track}/ajax-reserve', 'OrderController@ajaxReserve')->name('track.ajax-reserve');
    Route::patch('track/ajax-unreserve/', 'OrderController@ajaxUnReserve')->name('track.ajax-unreserve');
    Route::post('ajax-create', 'OrderController@ajaxCreate')->name('order.ajax-create');
    Route::post('ajax-approve', 'OrderController@ajaxApprove')->name('order.ajax-approve');
    Route::post('ajax-pending', 'OrderController@ajaxPending')->name('order.ajax-pending');
    Route::post('ajax-decline', 'OrderController@ajaxDecline')->name('order.ajax-decline');
});

//Route::get('/chats', 'ChatController@index');
Route::get('/messages', 'ChatController@fetchMessages');
Route::middleware('auth:web')->middleware('isHasTracks')->middleware('isChatBlocked')->post('/messages', 'ChatController@sendMessage');

app/Track.php
<?php

namespace App;

use App\Services\TracksByDistances;
use App\Services\TracksByPosition;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class Track extends Model
{
    const IMG_PATH = 'images/tracks/';
    const DEFAULT_IMG = self::IMG_PATH . 'default.png';
    const DEFAULT_POSITION = [ 'lat' => 59.91273, 'lon' => 10.74609];

    public $statuses = [
        'pending' => 'pending',
        'checked' => 'checked',
        'deny' => 'deny',
    ];

    protected $fillable = [
        'lon', 'lat', 'title', 'content', 'video', 'amount'
    ];

    public static function countTrackPerQuery()
    {
        return Auth::user() && Auth::user()->isTracking() ? env('TRACKS_PER_QUERY_FOR_ADMIN') : env('TRACKS_PER_QUERY') ;
    }

    public function owner()
    {
        return $this->belongsTo('App\User', 'user_id', 'id');
    }

    public function reserve()
    {
        return $this->hasOne('App\Reserve', 'id', 'reserve_id');
    }

    public static function currentPosition()
    {
        $current = self::where('isCurrent', 1)->first();

        if(!$current){
            $current = self::where('id', 1)->first();
        }

        return $current;
    }

    public function sibilings(int $count = 1000)
    {
//        $tracksService = new TracksByDistances($this);
        $tracksService = new TracksByPosition($this);

        $this->checkTracksReserve($tracksService->tracks);

        return $tracksService->tracks;
    }

    public function getImg()
    {
        return $this->img ? $this->img : self::DEFAULT_IMG ;
    }

    public function setLastTrackContent()
    {
        $current = self::currentPosition();

        if($current && $current->id > 1) {
            $nearest = self::where('id', '<', $current->id)->whereNull('order_id')->orderBy('id', 'desc')->first();
            if($nearest->id != $this->id) return;
        }

        if(!empty($nearest)){
            $shortNew = (new ShortNew())->latest()->first();
        }

        if(!empty($nearest) && !empty($shortNew)){
            $this->content = $shortNew->content;
        }
    }

    public function isInPaymentProcess()
    {
        if(($this->reserve && $this->reserve->order) && !$this->order_id){
            return true;
        }
    }

    public static function nearestBy($position)
    {
        $query = 'SELECT id, ( 3959 * acos( cos( radians('.$position['lat'].') ) * cos( radians( lat ) ) * ';
        $query = $query.'cos( radians( lon ) - radians('.$position['lon'].') ) + sin( radians('.$position['lat'].') ) * ';
        $query = $query.'sin( radians( lat ) ) ) ) AS distance FROM tracks HAVING ';
        $query = $query.'distance < 10000 ORDER BY distance LIMIT 0 , 1';

        $nearest = DB::select($query);

        return $nearest[0]->id;
    }

    public static function setCurrent($id)
    {
        $track = self::find($id);
        $track->isCurrent = 1;
        return $track->save();
    }

    public static function unsetOldCurrent($id)
    {
        $oldCurrent = self::currentPosition();
        $oldCurrent->isCurrent = 0;
        return $oldCurrent->save();
    }

    public function isReserved(){
        if($this->reserve){
            if($this->reserve->isActual()){
                return true;
            }else{
                $this->reserve_id = null;
                $this->save();
            }
        }

        return false;
    }

    public function isBought(){
        return !$this->owner->canAdmin();
    }

    private function checkTracksReserve($tracks)
    {
        foreach($tracks as $track){
            if($track->reserve){
                $track->isReserved();
            }
        }
    }
}

app/Http/Controllers/admin/TrackController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Track;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class TrackController extends Controller
{
    protected $trackPerPage = 500;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if(!$request->page) {
            $all = Track::where('isCurrent', '<=', '1')->pluck('isCurrent');
            $posCurent = array_search('1', $all->toArray());
            $page = ceil($posCurent / $this->trackPerPage);
            $tracks = Track::with('owner')->paginate( $this->trackPerPage, ['*'], 'page', $page);
        }else{
            $tracks = Track::with('owner')->paginate( $this->trackPerPage);
        }

        return view('admin.track.index', compact('tracks'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function bulkStore(Request $request)
    {
        if(!$request->tracksfile){
            return back()->with('success', 'Треба додати файл зі слідами');
        }

        $path = $request->tracksfile->path();
        $tracks = simplexml_load_file($path)->trk->trkseg->trkpt;
        foreach ($tracks as $key => $track){
            $model = new Track();
            foreach ($track->attributes() as $key => $value) {
                if($key == 'lat' || $key == 'lon'){
                    $model->$key = $value->__toString();
                }
            }
            $model->save();
        }

        return back()->with('success', 'Cліди додані!');
    }

    public function setCurrent(Request $request)
    {
        $oldCurrent = Track::currentPosition();

        if($oldCurrent && $oldCurrent->id == $request->trackId){
            return back()->with('default', 'Ви залишаєтесь на томуж місці!');
        }

        if(Track::setCurrent($request->trackId)) {

            if($oldCurrent) {
                $oldCurrent->isCurrent = 0;
                $oldCurrent->save();
            }
            return back()->with('success', 'Ви перемістилися! :)');
        }

        return back()->with('error', 'Щось нетак :(');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\track  $track
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $track = Track::findOrFail($id);

        return view('admin.track.edit', compact('track'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\track  $track
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Track $track)
    {
        $track->status = $request->status;

        if($request->file()){
            $track->img = $request->img->store($track::IMG_PATH);
        }

        if($track->update($request->all())){
            return back()->with('success', 'Cлід оновлено!');
        }

        return back()->with('error', 'Помилка оновлення сліду!');
    }
}

resources/views/admin/track/edit.blade.php
@extends('layouts.admin')

@section('title', 'Сліди')
@section('h1_title', 'Сліди')

@section('content')

    <div class="row">
        <div class="col-xs-12">
            <div class="box box-primary container">
                <div class="row">
                    {!! Form::model($track, ['route' => ['track.update', $track->id], 'method' => 'patch', 'enctype' => 'multipart/form-data']) !!}

                    <div class="col-xs-12 col-sm-6">
                        <div class="form-group">
                            {!! Form::label('lon', 'Lon *:') !!}
                            {!! Form::text('lon', null, ['class' => 'form-control']) !!}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6">
                        <div class="form-group">
                            {!! Form::label('lat', 'Lat *:') !!}
                            {!! Form::text('lat', null, ['class' => 'form-control']) !!}
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-6">
                        <div class="form-group">
                            {!! Form::label('owner[name]', 'Власник *:') !!}
                            {!! Form::text('owner[name]', null, ['class' => 'form-control', 'readonly']) !!}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6">
                        <div class="form-group">
                            {!! Form::label('status', 'Статус *:') !!}

                            <select class="form-control" id="status" name="status">
                                <option value="checked" {{ $track->status == 'checked' ? 'selected' : '' }}>checked</option>
                                <option value="pending" {{ $track->status == 'pending' ? 'selected' : '' }}>pending</option>
                                <option value="deny" {{ $track->status == 'deny' ? 'selected' : '' }}>deny</option>
                            </select>
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-6">

                        @if($track->video)
                            <div class="">
                                <iframe width="100%" height="auto" src="{{ $track->video }}"
                                        frameborder="0"
                                        allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                                        allowfullscreen></iframe>
                            </div>
                        @endif

                        <div class="form-group">
                            {!! Form::label('video', 'Відео :') !!}
                            {!! Form::text('video', null, ['class' => 'form-control']) !!}
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6">
                        @if($track->img)
                            <div class="">
                                <img src="/{{ $track->img}}" class="img-responsive" id="preview-img">
                            </div>
                        @endif
                        <div class="form-group">
                            {!! Form::label('img', 'Зображення :') !!}
                            {!! Form::file('img', ['class' => 'form-control image-upload']) !!}
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-6">
                        <div class="form-group">
                            {!! Form::label('amount', 'Ціна:') !!}
                            {!! Form::text('amount', null, ['class' => 'form-control']) !!}
                        </div>
                    </div>

                    <div class="col-xs-12">

                        <div class="form-group">
                            {!! Form::label('title', 'Назва:') !!}
                            {!! Form::text('title', null, ['class' => 'form-control']) !!}
                        </div>
                        <div class="form-group note-editor-page">
                            {!! Form::label('content', 'Зміст:') !!}
                            <textarea class="form-control text-editor" name="content" cols="50" rows="10" id="value-text">
                                {!!  $track->content !!}
                            </textarea>
                        </div>
                    </div>

                    <div class="form-group col-xs-12">
                        <input type="submit" value="Оновити слід" class="btn btn-primary">
                    </div>
                    {!! Form::close() !!}
                </div>

            </div>
        </div>
    </div>

@endsection

@section('inner_js')
    <script>
        $('.text-editor').summernote({
            height: 250
            }
        );
    </script>
@stop

resources/views/admin/track/index.blade.php
@extends('layouts.admin')

@section('title', 'Сліди')
@section('h1_title', 'Сліди')

@section('content')

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    {{--<a href="{{ route('track.create') }}" class="btn btn-primary">Create</a>--}}
                    <form role="form" action="{{ route('track.bulkStore') }}" method="post" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="exampleInputFile">Виберіть файл слідів</label>
                            <input type="file" name="tracksfile" id="exampleInputFile">
                        </div>

                        <button type="submit" class="btn btn-primary">Завантажити</button>
                    </form>
                </div>

                <div class="box-body">
                    <table id="tracks_table" class="table table-bordered table-hover dataTable" role="grid" aria-describedby="tracks_table_info">
                        <thead>
                            <tr role="row">
                                <th class="sorting_desc" tabindex="0" aria-controls="tracks_table" rowspan="1" colspan="1" >Id Сліда</th>

                                <th class="sorting" tabindex="0" aria-controls="tracks_table" rowspan="1" colspan="1">Назва</th>
                                <th class="sorting" tabindex="0" aria-controls="tracks_table" rowspan="1" colspan="1">Власник</th>
                                <th class="sorting" tabindex="0" aria-controls="tracks_table" rowspan="1" colspan="1">lat</th>
                                <th class="sorting" tabindex="0" aria-controls="tracks_table" rowspan="1" colspan="1">lon</th>
                                <th class="" tabindex="0" aria-controls="tracks_table" rowspan="1" colspan="1">Статус</th>
                                <th tabindex="0" aria-controls="tracks_table" rowspan="1" colspan="1"></th>
                            </tr>
                        </thead>

                        <tbody>
                        @forelse($tracks as $track)
                            <tr role="row" class="odd {{ $track->isCurrent ? 'current-track' : '' }}">
                                <td class="sorting_1"><a href="{{ route('track.edit', $track->id) }}">{{ $track->id }}</a></td>

                                <td><a href="{{ route('track.edit', $track->id) }}">{{ $track->title }}</a></td>
                                <td><a href="{{ route('track.edit', $track->id) }}">{{ $track->owner->name }}</a></td>
                                <td><a href="{{ route('track.edit', $track->id) }}">{{ $track->lat }}</a></td>
                                <td><a href="{{ route('track.edit', $track->id) }}">{{ $track->lon }}</a></td>

                                <td>
                                    @if($track->status == 'checked')
                                        <span class="label label-default">{{ $track->status }}</span>
                                    @elseif($track->status == 'deny')
                                        <span class="label label-warning">{{ $track->status }}</span>
                                    @elseif($track->status == 'pending')
                                        <span class="label label-info">{{ $track->status }}</span>
                                    @else
                                        <span class="label label-danger">{{ $track->status }}</span>
                                    @endif
                                </td>

                                <td>
                                    @if($track->isCurrent == 0)
                                    {{ Form::open(array('url' => route('track.setCurrent'), 'method' => 'post', 'class'=>'col-md-12')) }}
                                        {!! Form::hidden('trackId', $track->id) !!}
                                        {!! Form::button('Я тут!', [ 'type'=>'submit', 'class' => 'btn btn-primary']) !!}
                                    {{ Form::close() }}
                                    @endif
                                </td>
                            </tr>
                        @empty

                        @endforelse
                        </tbody>

                        <tfoot>
                            <tr>
                                <th class="sorting_desc" tabindex="0" aria-controls="tracks_table" rowspan="1" colspan="1" >Id Сліда</th>

                                <th class="sorting" tabindex="0" aria-controls="tracks_table" rowspan="1" colspan="1">Назва</th>
                                <th class="sorting" tabindex="0" aria-controls="tracks_table" rowspan="1" colspan="1">Власник</th>
                                <th class="sorting" tabindex="0" aria-controls="tracks_table" rowspan="1" colspan="1">lat</th>
                                <th class="sorting" tabindex="0" aria-controls="tracks_table" rowspan="1" colspan="1">lon</th>
                                <th class="" tabindex="0" aria-controls="tracks_table" rowspan="1" colspan="1">Статус</th>
                                <th class="" tabindex="0" aria-controls="tracks_table" rowspan="1" colspan="1"></th>
                            </tr>
                        </tfoot>
                    </table>

                    {{ $tracks->render() }}
                </div>

            </div>
        </div>
    </div>

@endsection

@section('inner_js')
    <script>
        $(function () {
            $('#tracks_table').DataTable({
                // 'paging'      : true,
                // 'lengthChange': false,
                'searching'   : false,
                paging: false,
                // 'ordering'    : true,
                'info'        : false,
                // 'autoWidth'   : false,
                // 'order': [[ 9, 'desc' ]]
            });
        });
    </script>
@stop